config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'application#index'
  post '/', to: 'application#search'

  resources :tournament, only: [:new, :create, :show] do
    get 'rankings'
    get 'countdown'
	get 'help'
    get 'schedule'
    post 'start_countdown'
	resources :round
	resources :player, only: [:new, :create] do
      get 'success'
	end
	resources :chombo, only: [:new, :create]
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :tournament
  has_many :chombos, dependent: :destroy
  has_many :player_rounds, dependent: :destroy
  validate :unique_name

  def unique_name
    errors.add(:name, "A player with this name already exists in the tournament.") if tournament.players.where(name: self.name).count > 0
  end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  before_action :set_tournament, only: [:create]

  def new
    @player = Player.new
  end

  def create
    @player.new(player_params.merge(tournament: @tournament))

    if @player.save
      redirect to player_success_url
    else
      render :new
    end
  end
  
  def success

  end

  def player_params
    params.require(:tournament).permit(
      :name
    )
  end
end

app/views/player/new.html.haml
= render partial: "shared/error", locals: {object: @tournament}

.row.justify-content-center
  %h1{ class: "pb-5" } Player Registration
  = form_for :player, url: player_index_url do |f|
    .form-group
      %label{for: :player_name} 
        Name
      = f.text_field :name, class: "form-control"
    = f.submit "Register", class: "btn btn-primary"

app/views/player/success.html.haml
= render partial: "shared/error", locals: {object: @tournament}

%div
  Congratulations! You have successfully registered for the tournament.