config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'application#index'
  post '/', to: 'application#search'

  resources :tournament, only: [:new, :create, :show] do
    get 'rankings'
    get 'countdown'
	get 'help'
    get 'schedule'
    post 'start_countdown'
	resources :round
	resources :player, only: [:new, :create] do
      get 'success'
	end
	resources :chombo, only: [:new, :create]
  end
end

app/views/shared/_error.html.haml
- if object.errors.any?
  #errors
    %h4
      = pluralize(object.errors.count, "error")
      %ul
        - object.errors.full_messages.each do |msg|
          %li= msg

app/views/shared/_navigation.html.haml
%nav{ class: "navbar navbar-light navbar-expand-lg secondary-bg" }
  .container-fluid
    =link_to "Riichi Tournaments", "#", class: "navbar-brand"
    %button{ type: "button", class: "navbar-toggler", "data-toggle": "collapse", "data-target": "#navbarMain", "aria-controls": "navbarMain", "aria-expanded": :false, "aria-label": "Toggle navigation" }
      %span{ class: "navbar-toggler-icon"}
    .collapse.navbar-collapse#navbarMain
      %ul{ class: "navbar-nav mr-auto mt-2 mt-lg-0" }
        %li{ class: "nav-item" }
          = link_to "Main", tournament_url(@tournament.alpha_id), class: "mr-4 navbar-text"
        %li{ class: "nav-item" }
          = link_to "Rankings", tournament_rankings_url(@tournament.alpha_id), class: "mr-4 navbar-text"
        %li{ class: "nav-item" }
          = link_to "Countdown", tournament_countdown_url(@tournament.alpha_id), class: "mr-4 navbar-text"
          - if @tournament.schedule.present?
            %li{ class: "nav-item" }
              = link_to "Schedule", tournament_schedule_url(@tournament.alpha_id), class: "mr-4 navbar-text"
          -if authorized?(@tournament, :edit?)
            %li{ class: "nav-item" }
              = link_to "New Game", new_tournament_round_url(@tournament.alpha_id), class: "mr-4 navbar-text"
            %li{ class: "nav-item" }
              = link_to "Help", tournament_help_url(@tournament.alpha_id), class: "mr-4 navbar-text"

//%nav{ class: "navbar secondary-bg navbar-expand-lg" }
//.container-fluid
//  %ul{ class: "nav navbar-nav" }
//    %li
//      = link_to "Main", tournament_url(@tournament.alpha_id), class: "mr-4 navbar-text"
//      = link_to "Rankings", tournament_rankings_url(@tournament.alpha_id), class: "mr-4 navbar-text"
//      = link_to "Countdown", tournament_countdown_url(@tournament.alpha_id), class: "mr-4 navbar-text"
//      - if @tournament.schedule.present?
//        = link_to "Schedule", tournament_schedule_url(@tournament.alpha_id), class: "mr-4 navbar-text"
//      -if authorized?(@tournament, :edit?)
//        = link_to "New Game", new_tournament_round_url(@tournament.alpha_id), class: "mr-4 navbar-text"
//        = link_to "Help", tournament_help_url(@tournament.alpha_id), class: "mr-4 navbar-text"