config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'application#index'
  post '/', to: 'application#search'

  resources :tournament, only: [:new, :create, :show] do
    get 'rankings'
    get 'countdown'
	get 'help'
    get 'schedule'
    post 'start_countdown'
	resources :round
	resources :player, only: [:new, :create] do
      get 'success'
	end
	resources :chombo, only: [:new, :create]
  end
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :tournament
  has_many :player_rounds, dependent: :destroy

  def score_oka
    players = player_rounds.order(score: :desc, wind: :asc)
    uma = [tournament.oka_first * 1000, tournament.oka_second * 1000, tournament.oka_third * 1000, tournament.oka_fourth * 1000]
    diff = (30000 - tournament.start_score) * 4

    player_rounds.find(players[0].id).update(oka: ((players[0].score.round(-3) - 30000 + uma.first + diff )   / 1000))
    player_rounds.find(players[1].id).update(oka: ((players[1].score.round(-3) - 30000 + uma.second)          / 1000))
    player_rounds.find(players[2].id).update(oka: ((players[2].score.round(-3) - 30000 + uma.third)           / 1000))
    player_rounds.find(players[3].id).update(oka: ((players[3].score.round(-3) - 30000 + uma.fourth)          / 1000))
  end

end

app/controllers/round_controller.rb
class RoundController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit]

  def new
    @tournament = Tournament.find_by_alpha_id(params[:tournament_id])
    @round = Round.new
	#@player_list = @tournament.pick_matches
  end

  def edit
    @tournament = Tournament.find_by_alpha_id(params[:tournament_id])
    @round = @tournament.rounds.find_by(id: params[:id])

    authorize @round
  end

  def update
    @tournament = Tournament.find_by_alpha_id(params[:tournament_id])
    @round = @tournament.rounds.find_by(id: params[:id])
    authorize @round
    
    params[:players].each_with_index do |v, i|
      player_round = PlayerRound.find_by(round: @round, player_id: @tournament.players.find_by_name(v))
      player_round.update!(score: params[:start_score][i])
    end
    @round.score_oka
    redirect_to tournament_round_index_url(@tournament.alpha_id)
  end

  def show
    @tournament = Tournament.find_by_alpha_id(params[:tournament_id])
    @rounds = @tournament.rounds.where(round_number: (params[:id].to_i)).order(order: :asc)
  end

  def index
    @tournament = Tournament.find_by_alpha_id(params[:tournament_id])
    @rounds = @tournament.rounds.order(round_number: :asc, order: :asc)
  end

  def create
    @tournament = Tournament.find_by_alpha_id(params[:tournament_id])
    curr_round = @tournament.current_round_number
    authorize(@tournament, :edit?)

    #A game hasn't been finished/completed.
    # @tournament.player_rounds.count > 0 && 
    if @tournament.player_rounds.where(round_id: @tournament.rounds.where(round_number: curr_round).map(&:round_number)).where(score: nil, oka: nil).count != 0
      flash[:error] = "Current game has not been completed."
      redirect_to tournament_url(@tournament.alpha_id)
      return
    end

    i = 0
    until i > @tournament.max_games do
      if params[:players][i].present? && params[:players][i + 1].present? && params[:players][i + 2].present? && params[:players][i + 3].present?
        @round = Round.create!(round_number: curr_round + 1, order: i, tournament: @tournament,
          player_rounds: [
            PlayerRound.new(tournament: @tournament, player: @tournament.players.find_by_name(params[:players][i    ]), wind: 0),
            PlayerRound.new(tournament: @tournament, player: @tournament.players.find_by_name(params[:players][i + 1]), wind: 1),
            PlayerRound.new(tournament: @tournament, player: @tournament.players.find_by_name(params[:players][i + 2]), wind: 2),
            PlayerRound.new(tournament: @tournament, player: @tournament.players.find_by_name(params[:players][i + 3]), wind: 3)
            ])
      end
      i += 4
    end
    if @round.invalid?
      render :new
      return
    end
    redirect_to tournament_url(@tournament.alpha_id)
  end

  def round_params
    params.require(:players)
  end
end

app/views/round/_show.html.haml
%h4= "Round #{@round.round_number} Match #{@round.order + 1}"

= link_to 'Edit', edit_tournament_round_url(@tournament.alpha_id, @round)
%table{ class: "table table-bordered table-striped" }
  %thead
    %tr
      %th Wind
      %th Player Name
      %th Score
      %th Oka
  %tbody
    -@round.player_rounds.each do |player|
      %tr
        %td= player.wind.to_s.humanize
        %td= player.player.name.to_s
        %td= player.score.to_s
        %td= player.oka.to_s
    

app/views/round/edit.html.haml
= form_tag tournament_round_url(@tournament.alpha_id, @round), method: :put do |t|
  - player_rounds = @round.player_rounds.order(wind: :asc)
  %table{ class: "table table-bordered table-striped" }
    %thead
      %tr
        %th Wind
        %th Player Name
        %th Score
    %tbody
      %tr
        %td East
        %td
          = text_field_tag "players[]", player_rounds[PlayerRound.winds[:east]].player.name
        %td
          = number_field_tag "start_score[]", player_rounds[PlayerRound.winds[:east]].score || @tournament.start_score, step: 1000
      %tr
        %td South
        %td
          = text_field_tag "players[]", player_rounds[PlayerRound.winds[:south]].player.name
        %td
          = number_field_tag "start_score[]", player_rounds[PlayerRound.winds[:south]].score || @tournament.start_score, step: 1000
      %tr
        %td West
        %td
          = text_field_tag "players[]", player_rounds[PlayerRound.winds[:west]].player.name
        %td
          = number_field_tag "start_score[]", player_rounds[PlayerRound.winds[:west]].score || @tournament.start_score, step: 1000
      %tr
        %td North
        %td
          = text_field_tag "players[]", player_rounds[PlayerRound.winds[:north]].player.name
        %td
          = number_field_tag "start_score[]", player_rounds[PlayerRound.winds[:north]].score || @tournament.start_score, step: 1000
  = submit_tag "Save", class: "btn btn-primary"

app/views/round/index.html.haml
= render partial: "shared/navigation"

%h2{ style: "text-align: center;" }=@tournament.name
- @rounds.each do |round|
  .container
    - @round = round
    = render partial: 'round/show'

app/views/round/new.html.haml
= render partial: "shared/navigation"

.row.justify-content-center
  .col-md-4.col-xs-12
    %p Enter the players who will be in the same match. Please only use the exact names of players who were entered as participants when creating the tournament.
= form_tag tournament_round_index_url(@tournament.alpha_id) do |t|
  .row.justify-content-center
    //.col-6
    //%table{ class: "table table-bordered table-striped text-center" }
    //  %thead
    //    %tr
    //      %th Players
    //  %tbody
    //    - @tournament.players.each do |p|
    //      %tr
    //        %td= p.name
    - i = 1
    -until i > @tournament.max_games do
      .col-md-auto
        - if @round.present?
          - @round.player_rounds.each do |pr|
            = render partial: "shared/error", locals: {object: pr}
        %table{ class: "table table-bordered table-striped text-center" }
          %thead
            %tr
              %th Wind
              %th Player
          %tbody
            %tr
              %td East
              %td
                -#round_list = @player_list.shift
                = text_field_tag "players[]", nil, class: "form-control", list: "player-list#{0 + ((i - 1) * 4)}", autocomplete: :off 
                %datalist{ id: "player-list#{0 + ((i - 1) * 4)}" }
                  =@tournament.decorate.player_list
            %tr
              %td South
              %td
                = text_field_tag "players[]", nil, class: "form-control", list: "player-list#{1 + ((i - 1) * 4)}", autocomplete: :off
                %datalist{ id: "player-list#{1 + ((i - 1) * 4)}" }
                  =@tournament.decorate.player_list
            %tr
              %td West
              %td
                = text_field_tag "players[]", nil, class: "form-control", list: "player-list#{2 + ((i - 1) * 4)}", autocomplete: :off
                %datalist{ id: "player-list#{2 + ((i - 1) * 4)}" }
                  =@tournament.decorate.player_list
            %tr
              %td North
              %td
                = text_field_tag "players[]", nil, class: "form-control", list: "player-list#{3 + ((i - 1) * 4)}", autocomplete: :off
                %datalist{ id: "player-list#{3 + ((i - 1) * 4)}" }
                  =@tournament.decorate.player_list
      -i += 1
  .row.justify-content-center
    = submit_tag "Start New Round", class: "btn btn-primary btn-lg"

app/views/round/show.html.haml
= render partial: "shared/navigation"

%h2{ style: "text-align: center;" }=@tournament.name
- @rounds.each do |round|
  .container
    - @round = round
    = render partial: 'round/show'