config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'application#index'
  post '/', to: 'application#search'

  resources :tournament, only: [:new, :create, :show] do
    get 'rankings'
    get 'countdown'
	get 'help'
    get 'schedule'
    post 'start_countdown'
	resources :round
	resources :player, only: [:new, :create] do
      get 'success'
	end
	resources :chombo, only: [:new, :create]
  end
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :rounds, dependent: :destroy
  has_many :players, dependent: :destroy
  has_many :player_rounds, dependent: :destroy

  belongs_to :user

  validate :oka_compare
  validate :validate_players
  validates_presence_of :name
  validates :total_rounds, numericality: { greater_than_or_equal_to:  0 }
  validates :time_limit, numericality: { greater_than_or_equal_to:  0 }
  validates :start_score, numericality: { greater_than_or_equal_to:  0 }
  validates :oka_first, numericality: { greater_than:  0 }
  validates :oka_second, numericality: { greater_than:  0 }

  before_create :setup

  def initialize(args = {})
    super(args)
  end

  def setup
    value = ""; 5.times{value << (65 + rand(25)).chr}
    self.alpha_id = value
  end

  def oka_third
    -self.oka_second
  end

  def oka_fourth
    -self.oka_first
  end

  def current_round
    self.rounds.select(:round_number).order(round_number: :desc).first
  end

  def current_round_number
    self.rounds.order(round_number: :desc).max.try(:round_number) || 0
  end

  def schedule=(value)
    write_attribute(:schedule, nil) if value.nil?
    write_attribute(:schedule, ActionView::Base.full_sanitizer.sanitize(value).gsub(/\R+/, "<br>"))
  end

  def max_games
    players.count / 4
  end

  def players_rank
    #ActiveRecord::Base.connection.exec_query("SELECT player_id, SUM(oka) as sum_oka FROM player_rounds WHERE player_rounds.tournament_id = #{id} GROUP BY player_id ORDER BY sum_oka DESC").rows
    rows = ActiveRecord::Base.connection.exec_query("
      SELECT player_rounds.player_id, SUM(oka) - ((SELECT COUNT(*) FROM chombos ch WHERE player_rounds.player_id = ch.player_id) * #{self.chombo_cost}) as sum_oka 
        FROM player_rounds WHERE player_rounds.tournament_id = #{self.id}
        GROUP BY player_rounds.player_id 
        ORDER BY sum_oka DESC").rows
    rows = ActiveRecord::Base.connection.exec_query("
      SELECT players.id, 0
        FROM players WHERE players.tournament_id = #{self.id}
        ORDER BY players.id ASC").rows if rows.empty?
    return rows
  end

  def oka_compare
    if oka_first < oka_second
      errors.add(:base, "Oka first must be greater than oka second.")
    end
  end

  def validate_players
    errors.add(:players, "Not enough players") if players.length < 4
  end

  #For every player figure out how many matches they have played with every player
  #Then sort this list and pick max_games leaders. These leaders will then one at
  #a time pick the player from their generated list that has played the least
  #amount of games with the leader.
  def pick_matches
    matches = Struct.new(:player_lookup, :played_table, :leaders).new({ }, Array.new(players.count), [])
    sorted_arr = []
    # An array of hash tables each element of played_table represents the nth player found in the tournaments.player array.
    # Each table's key is the player's id, and the value is how many times that player has been played the person 
    # represented by the array.

    matches.played_table.each_with_index do |item, index|
      matches.played_table[index] = { }
	  players.each do |p|
        matches.played_table[index][p.id] = 0
      end
    end
	player_ids = players.map(&:id)
	player_idx = {}
	players.each_with_index do |item, index|
      player_idx[item.id] = index
	end
    matches.leaders << player_ids.sample
     (max_games - 1).times do |i|
      begin
        rand_number = player_ids.sample
        matches.leaders << rand_number unless matches.leaders.include?(rand_number)
      end while matches.leaders.count <= (i + 1)
    end

    players.each_with_index do |p, i|
      matches.player_lookup[p.id] = i
    end
    players.each_with_index do |p, i|
      played = player_rounds.select(:player_id).where(round_id: PlayerRound.select(:round_id).where(player: p)).where.not(player: p).group(:player_id).map(&:player_id)
      played.each do |o|
        #matches.played_table[i][matches.player_lookup[o]] = matches.played_table[i][matches.player_lookup[o]] + 1
        matches.played_table[i][o] = matches.played_table[i][o] + 1
      end
    end
    matches.played_table.each do |a|
      sorted_arr << a.sort_by(&:last) 
    end
    #Done initializing data.

    pick_list = matches.leaders.dup #Players who have already been picked.
    games = Array.new(max_games)
    games.each_with_index do |item, index|
      games[index] = Array.new(4)
      games[index][0] = matches.leaders[index]
    end

    for i in 1..3
      matches.leaders.each_with_index do |picker, index|
		picker = player_idx[picker]
        begin
          #keep picking until we find a non-picked player.
          games[index][i] = sorted_arr[picker].shift.first
        end while pick_list.include?(games[index][i])
        pick_list << games[index][i]
        new_scores = score_players(matches, games[index], matches.player_lookup[sorted_arr[picker].shift.first])
        #Resort the sorted_arr adding penalties to players who haven't been chosen but have already played chosen players.
        sorted_arr[picker].map.with_index.sort_by do |item, index|
          new_scores[index]
        end
      end
    end
    return games.map do |array|
      array.map do |item|
        Player.find(item)
      end
    end
  end

  def score_players matches, game, player_index
    scores = Array.new(matches.played_table[player_index].size).fill(0)

    matches.played_table[player_index].each do |key, val|
      index = matches.player_lookup[key]
      game.each do |item|
        next if matches.played_table[index][item].nil?
        scores[index] += matches.played_table[index][item]
      end
    end
    return scores
  end
end

app/controllers/tournament_controller.rb
class TournamentController < ApplicationController
  before_action :set_tournament, except: [:show, :create]

  def show
    @tournament = Tournament.find_by_alpha_id(params[:id])
  end

  def countdown
  end

  def rankings
  end

  def help
  end

  def schedule
  end

  def new
    @tournament = Tournament.new
    @participants = ""
  end

  def start_countdown
    authorize @tournament, :edit?
    @tournament.update!(countdown: DateTime.now.utc)
    redirect_to tournament_countdown_url(@tournament.alpha_id)
  end

  def create
    @participants = params[:participants]
    @user = User.new
    @tournament = Tournament.new(tournament_params.merge(players: @participants.split("\r\n").map do |player| Player.new(tournament: @tournament, name: player) end, user: @user))

    if @tournament.invalid?
      render :new
      return
    end

    @tournament.save
    @user.email = "#{@tournament.alpha_id}@test.com"
    @user.save
    sign_in(@user)
    redirect_to tournament_url(@tournament.alpha_id)
  end

  def tournament_params
    params.require(:tournament).permit(
      :name, :total_rounds, :time_limit, :start_score, :oka_first, :oka_second, :schedule
    )
  end
end

app/views/tournament/countdown.html.haml
= render partial: "shared/navigation"

.row.justify-content-center.pt-5
  %h1{ id: :countdown, style: "font-size: 64px;"}
-if authorized? @tournament, :edit?
  .row.justify-content-center.pt-3
    = button_to "Start Game", tournament_start_countdown_url(@tournament.alpha_id), class: "btn btn-primary"

-if @tournament.countdown.present?
  :javascript
    var countDownDate = new Date("#{(@tournament.countdown.to_datetime + @tournament.time_limit.to_i.minutes).strftime("%b %d %Y %H:%M:%S")}").getTime()
    var x = setInterval(function() {
      var now = new Date();
      now = now.getTime() + (now.getTimezoneOffset() * 60000)
      var distance = countDownDate - now;
  
      var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
      var seconds = Math.floor((distance % (1000 * 60)) / (1000));
  
      document.getElementById("countdown").innerHTML = ("0" + hours).slice(-2) + ":" + ("0" + minutes).slice(-2) + ":" + ("0" + seconds).slice(-2);
      if(distance < 0) {
        clearInterval(x);
        document.getElementById("countdown").innerHTML = "00:00:00";
      }
    }, 1000);
-else 
  :javascript
    document.getElementById("countdown").innerHTML = "00:00:00"

app/views/tournament/help.html.haml
= render partial: "shared/navigation"
%div{ style: "max-width: 38rem; margin: auto;" }
  %p
    Your tournament code is: 
    %b= @tournament.alpha_id
  %p
    Give this code to your players to allow them to view your tournament. Players are unable to change the tournament.
  %p
    To start a new game, click the new game button in the navigation bar. Then fill out the player names for everyone who is playing at each table.
    Once the game has been created, click on countdown in the navigation bar. Then click "Start Game" to start the countdown.
  %p
    When every game is completed, click on the current hanchan in the rankings menu, and then enter the scores of every player.
    If someone has commited a chombo during a game, click on chombo in the rankings menu and type in the player's name.

app/views/tournament/new.html.haml
.row.justify-content-center
  .xs-col-12.col-6
    .row.justify-content-center
      %h1{ class: "pb-5" } Create Tournament
    = render partial: "shared/error", locals: {object: @tournament}
    = form_for :tournament, url: tournament_index_url, html: { class: "form-horizontal" } do |f|
      .form-group
        %label{for: :tournament_name} 
          Tournament Name
        = f.text_field :name, class: "form-control"
      .form-group
        %label{for: :tournament_total_rounds}
          Total Matches
        = f.number_field :total_rounds, value: 4, class: "form-control"
      .form-group
        %label{for: :tournament_time_limit}
          Time Limit(minutes)
        = f.number_field :time_limit, value: 80, class: "form-control"
      .form-group
        %label{for: :tournament_start_score}
          Starting Score
        = f.number_field :start_score, value: 25000, step: 1000, class: "form-control"
      .form-group
        %label{for: :tournament_oka_first}
          Oka First Place
        = f.number_field :oka_first, value: 20, class: "form-control"
      .form-group
        %label{for: :tournament_oka_second}
          Oka Second Place
        = f.number_field :oka_second, value: 10, class: "form-control"
      .form-group
        %label{for: :tournament_participants}
          Participant List
        .div
          %small Enter one name per line
        = text_area_tag :participants, @participants, class: "form-control"
        %label{for: :tournament_schedule}
          Schedule contents
        .div
          %small Enter one name per line
        = f.text_area :schedule, class: "form-control"
      = f.submit "Create", class: "btn btn-primary"

app/views/tournament/rankings.html.haml
= render partial: "shared/navigation"

.row.justify-content-center.mt-5
  %table{ id: "rankings", class: "table table-bordered table-striped" }
    %thead
      %tr
        %th Rank
        %th Player
        - @tournament.total_rounds.times do |i|
          %th
            - if @tournament.rounds.where(round_number: i + 1).present?
              = link_to "Hanchan #{i + 1}", tournament_round_url(@tournament.alpha_id, i + 1)
            - else 
              = "Hanchan #{i + 1}"
        %th= link_to "Chombo", new_tournament_chombo_url
        %th Oka
    %tbody
      - rank = 1
      - @tournament.players_rank.each do |id, oka|
        -player = Player.find(id)
        %tr
          %td= rank.to_s
          %td= player.name
          - @tournament.total_rounds.times do |i|
            %td= PlayerRound.joins(:round).find_by(player: player, rounds: { round_number: i + 1 }).try(:oka) || "0"
          %td= Chombo.where(player: player).count * @tournament.chombo_cost || "0"
          %td= oka.to_s
        - rank = rank + 1
    

app/views/tournament/schedule.html.haml
= render partial: "shared/navigation"
.row.justify-content-center.mt-5
  %h1 Schedule

.row
  =@tournament.schedule.html_safe

app/views/tournament/show.html.haml
= render partial: "shared/navigation"

.row.justify-content-center.pt-5
  %h1 Tournament Rules
.container
  .row.justify-content-center
    %h1= @tournament.name
  .row.justify-content-center
    .mb-2= "Total Rounds: #{@tournament.total_rounds}"
  .row.justify-content-center
    .mb-2= "Time Limit: #{@tournament.time_limit} minutes"
  .row.justify-content-center
    .mb-2= "Starting Score: #{@tournament.start_score}"
  .row.justify-content-center
    .mb-2= "Oka: [#{@tournament.oka_first} #{@tournament.oka_second} #{@tournament.oka_third} #{@tournament.oka_fourth}]"